name: "web_app"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2020-11-01"
machine_id: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "database-gomysql.chvwwy2ex6ot.us-east-2.rds.amazonaws.com"
  port: 3306
  user: "admin"
  password: "MySQL4GO"
  db: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "35.243.147.176"
  port: 6379
  db: 0
  password: ""
  pool_size: 100